# Generated by Django 4.2.13 on 2024-06-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/photo", verbose_name="Превью"
            ),
        ),
    ]
